{
    "openapi": "3.1.0",
    "info": {
        "title": "DeviantArt API",
        "version": "1.20240701",
        "description": "OpenAPI specification generated from public /api endpoints."
    },
    "servers": [
        {
            "url": "https://www.deviantart.com/api/v1/oauth2"
        }
    ],
    "paths": {
        "/browse/dailydeviations": {
            "get": {
                "operationId": "browse_dailydeviations",
                "tags": [
                    "browse"
                ],
                "summary": "Daily Deviations",
                "description": "Browse daily deviations",
                "security": [
                    {
                        "oauth2AuthorizationCodeOrClientCredentials": [
                            "browse"
                        ]
                    }
                ]
            }
        },
        "/browse/deviantsyouwatch": {
            "get": {
                "operationId": "browse_deviantsyouwatch",
                "tags": [
                    "browse"
                ],
                "summary": "Deviations of deviants you watch",
                "description": "Get deviations of deviants you watch",
                "security": [
                    {
                        "oauth2AuthorizationCode": [
                            "browse"
                        ]
                    }
                ]
            }
        },
        "/browse/home": {
            "get": {
                "operationId": "browse_home",
                "tags": [
                    "browse"
                ],
                "summary": "Browse homepage",
                "description": "Browse homepage",
                "security": [
                    {
                        "oauth2AuthorizationCodeOrClientCredentials": [
                            "browse"
                        ]
                    }
                ]
            }
        },
        "/browse/morelikethis/preview": {
            "get": {
                "operationId": "browse_morelikethis_preview",
                "tags": [
                    "browse"
                ],
                "summary": "More Like This Preview",
                "description": "Fetch More Like This preview result for a seed deviation",
                "security": [
                    {
                        "oauth2AuthorizationCodeOrClientCredentials": [
                            "browse"
                        ]
                    }
                ]
            }
        },
        "/browse/tags": {
            "get": {
                "operationId": "browse_tags",
                "tags": [
                    "browse"
                ],
                "summary": "Tags",
                "description": "Browse a tag",
                "security": [
                    {
                        "oauth2AuthorizationCodeOrClientCredentials": [
                            "browse"
                        ]
                    }
                ]
            }
        },
        "/browse/tags/search": {
            "get": {
                "operationId": "browse_tags_search",
                "tags": [
                    "browse"
                ],
                "summary": "Tags Search",
                "description": "Autocomplete tags",
                "security": [
                    {
                        "oauth2AuthorizationCodeOrClientCredentials": [
                            "browse"
                        ]
                    }
                ]
            }
        },
        "/browse/topic": {
            "get": {
                "operationId": "browse_topic",
                "tags": [
                    "browse"
                ],
                "summary": "Topic",
                "description": "Fetch topic deviations",
                "security": [
                    {
                        "oauth2AuthorizationCodeOrClientCredentials": [
                            "browse"
                        ]
                    }
                ]
            }
        },
        "/browse/topics": {
            "get": {
                "operationId": "browse_topics",
                "tags": [
                    "browse"
                ],
                "summary": "Topics",
                "description": "Fetch topics and deviations from each topic",
                "security": [
                    {
                        "oauth2AuthorizationCodeOrClientCredentials": [
                            "browse"
                        ]
                    }
                ]
            }
        },
        "/browse/toptopics": {
            "get": {
                "operationId": "browse_toptopics",
                "tags": [
                    "browse"
                ],
                "summary": "Top Topics",
                "description": "Fetch top topics with example deviation for each one",
                "security": [
                    {
                        "oauth2AuthorizationCodeOrClientCredentials": [
                            "browse"
                        ]
                    }
                ]
            }
        },
        "/collections/all": {
            "get": {
                "operationId": "collections_all",
                "tags": [
                    "collections"
                ],
                "summary": "All deviations in user's collection",
                "description": "All deviations in user's collection",
                "security": [
                    {
                        "oauth2AuthorizationCodeOrClientCredentials": [
                            "browse"
                        ]
                    }
                ]
            }
        },
        "/collections/fave": {
            "post": {
                "operationId": "collections_fave",
                "tags": [
                    "collections"
                ],
                "summary": "Fave",
                "description": "Add deviation to favourites",
                "security": [
                    {
                        "oauth2AuthorizationCode": [
                            "browse",
                            "collection"
                        ]
                    }
                ]
            }
        },
        "/collections/folders": {
            "get": {
                "operationId": "collections_folders",
                "tags": [
                    "collections"
                ],
                "summary": "Collection Folders",
                "description": "Fetch collection folders",
                "security": [
                    {
                        "oauth2AuthorizationCodeOrClientCredentials": [
                            "browse"
                        ]
                    }
                ]
            }
        },
        "/collections/folders/copy_deviations": {
            "post": {
                "operationId": "collections_folders_copy_deviations",
                "tags": [
                    "collections"
                ],
                "summary": "Copy Deviations to folder",
                "description": "Copy a list of deviations to a folder destination",
                "security": [
                    {
                        "oauth2AuthorizationCode": [
                            "browse",
                            "collection"
                        ]
                    }
                ]
            }
        },
        "/collections/folders/create": {
            "post": {
                "operationId": "collections_folders_create",
                "tags": [
                    "collections"
                ],
                "summary": "Collection Folders Create",
                "description": "Create new collection folder",
                "security": [
                    {
                        "oauth2AuthorizationCode": [
                            "browse",
                            "collection"
                        ]
                    }
                ]
            }
        },
        "/collections/folders/move_deviations": {
            "post": {
                "operationId": "collections_folders_move_deviations",
                "tags": [
                    "collections"
                ],
                "summary": "Move Deviations to folder",
                "description": "Copy a list of deviations to a folder destination",
                "security": [
                    {
                        "oauth2AuthorizationCode": [
                            "browse",
                            "collection"
                        ]
                    }
                ]
            }
        },
        "/collections/folders/remove/{folderid}": {
            "get": {
                "operationId": "collections_folders_remove",
                "tags": [
                    "collections"
                ],
                "summary": "Collection Folders Remove",
                "description": "Delete collection folder",
                "security": [
                    {
                        "oauth2AuthorizationCode": [
                            "browse",
                            "collection"
                        ]
                    }
                ]
            }
        },
        "/collections/folders/remove_deviations": {
            "post": {
                "operationId": "collections_folders_remove_deviations",
                "tags": [
                    "collections"
                ],
                "summary": "Remove deviations from folder",
                "description": "Remove a list of deviations from a gallery folder",
                "security": [
                    {
                        "oauth2AuthorizationCode": [
                            "browse",
                            "collection"
                        ]
                    }
                ]
            }
        },
        "/collections/folders/update": {
            "post": {
                "operationId": "collections_folders_update",
                "tags": [
                    "collections"
                ],
                "summary": "Update details",
                "security": [
                    {
                        "oauth2AuthorizationCode": [
                            "browse",
                            "collection"
                        ]
                    }
                ]
            }
        },
        "/collections/folders/update_deviation_order": {
            "post": {
                "operationId": "collections_folders_update_deviation_order",
                "tags": [
                    "collections"
                ],
                "summary": "Update deviation order",
                "description": "Update order of deviation in folder",
                "security": [
                    {
                        "oauth2AuthorizationCode": [
                            "browse",
                            "collection"
                        ]
                    }
                ]
            }
        },
        "/collections/folders/update_order": {
            "post": {
                "operationId": "collections_folders_update_order",
                "tags": [
                    "collections"
                ],
                "summary": "Reposition a folder",
                "description": "Rearrange the position of folders",
                "security": [
                    {
                        "oauth2AuthorizationCode": [
                            "browse",
                            "collection"
                        ]
                    }
                ]
            }
        },
        "/collections/unfave": {
            "post": {
                "operationId": "collections_unfave",
                "tags": [
                    "collections"
                ],
                "summary": "Unfave",
                "description": "Remove deviation from favourites",
                "security": [
                    {
                        "oauth2AuthorizationCode": [
                            "browse",
                            "collection"
                        ]
                    }
                ]
            }
        },
        "/collections/{folderid}": {
            "get": {
                "operationId": "collections",
                "tags": [
                    "collections"
                ],
                "summary": "Collections",
                "description": "Fetch collection folder contents",
                "security": [
                    {
                        "oauth2AuthorizationCodeOrClientCredentials": [
                            "browse"
                        ]
                    }
                ]
            }
        },
        "/comments/deviation/{deviationid}": {
            "get": {
                "operationId": "comments_deviation",
                "tags": [
                    "comments"
                ],
                "summary": "Comments Deviation",
                "description": "Fetch comments posted on deviation",
                "security": [
                    {
                        "oauth2AuthorizationCodeOrClientCredentials": [
                            "browse"
                        ]
                    }
                ]
            }
        },
        "/comments/post/deviation/{deviationid}": {
            "post": {
                "operationId": "comments_post_deviation",
                "tags": [
                    "comments"
                ],
                "summary": "Comments Post Deviation",
                "description": "Post comment on a deviation",
                "security": [
                    {
                        "oauth2AuthorizationCode": [
                            "browse",
                            "comment.post"
                        ]
                    }
                ]
            }
        },
        "/comments/post/profile/{username}": {
            "post": {
                "operationId": "comments_post_profile",
                "tags": [
                    "comments"
                ],
                "summary": "Comments Post Profile",
                "description": "Post comment on a users profile",
                "security": [
                    {
                        "oauth2AuthorizationCode": [
                            "browse",
                            "comment.post"
                        ]
                    }
                ]
            }
        },
        "/comments/post/status/{statusid}": {
            "post": {
                "operationId": "comments_post_status",
                "tags": [
                    "comments"
                ],
                "summary": "Comments Post Status",
                "description": "Post comment on a status",
                "security": [
                    {
                        "oauth2AuthorizationCode": [
                            "browse",
                            "comment.post"
                        ]
                    }
                ]
            }
        },
        "/comments/profile/{username}": {
            "get": {
                "operationId": "comments_profile",
                "tags": [
                    "comments"
                ],
                "summary": "Comments Profile",
                "description": "Fetch comments posted on user profile",
                "security": [
                    {
                        "oauth2AuthorizationCodeOrClientCredentials": [
                            "browse"
                        ]
                    }
                ]
            }
        },
        "/comments/status/{statusid}": {
            "get": {
                "operationId": "comments_status",
                "tags": [
                    "comments"
                ],
                "summary": "Comments Status",
                "description": "Fetch comments posted on status",
                "security": [
                    {
                        "oauth2AuthorizationCodeOrClientCredentials": [
                            "browse"
                        ]
                    }
                ]
            }
        },
        "/comments/{commentid}/siblings": {
            "get": {
                "operationId": "comments_siblings",
                "tags": [
                    "comments"
                ],
                "summary": "Comments Siblings",
                "description": "Fetch siblings of a comment",
                "security": [
                    {
                        "oauth2AuthorizationCodeOrClientCredentials": [
                            "browse"
                        ]
                    }
                ]
            }
        },
        "/data/countries": {
            "get": {
                "operationId": "data_countries",
                "tags": [
                    "data"
                ],
                "summary": "Countries",
                "description": "Get a list of countries",
                "security": [
                    {
                        "oauth2AuthorizationCodeOrClientCredentials": [
                            "browse"
                        ]
                    }
                ]
            }
        },
        "/data/privacy": {
            "get": {
                "operationId": "data_privacy",
                "tags": [
                    "data"
                ],
                "summary": "Privacy Policy",
                "description": "Returns the DeviantArt Privacy Policy",
                "security": [
                    {
                        "oauth2AuthorizationCodeOrClientCredentials": [
                            "browse"
                        ]
                    }
                ]
            }
        },
        "/data/submission": {
            "get": {
                "operationId": "data_submission",
                "tags": [
                    "data"
                ],
                "summary": "Submission Policy",
                "description": "Returns the DeviantArt Submission Policy",
                "security": [
                    {
                        "oauth2AuthorizationCodeOrClientCredentials": [
                            "browse"
                        ]
                    }
                ]
            }
        },
        "/data/tos": {
            "get": {
                "operationId": "data_tos",
                "tags": [
                    "data"
                ],
                "summary": "Terms of Service",
                "description": "Returns the DeviantArt Terms of Service",
                "security": [
                    {
                        "oauth2AuthorizationCodeOrClientCredentials": [
                            "browse"
                        ]
                    }
                ]
            }
        },
        "/deviation/content": {
            "get": {
                "operationId": "deviation_content",
                "tags": [
                    "deviation"
                ],
                "summary": "Deviation Content",
                "description": "Fetch full data that is not included in the main devaition object",
                "security": [
                    {
                        "oauth2AuthorizationCodeOrClientCredentials": [
                            "browse"
                        ]
                    }
                ]
            }
        },
        "/deviation/download/{deviationid}": {
            "get": {
                "operationId": "deviation_download",
                "tags": [
                    "deviation"
                ],
                "summary": "Deviation Download",
                "description": "Get the original file download (if allowed)",
                "security": [
                    {
                        "oauth2AuthorizationCodeOrClientCredentials": [
                            "browse"
                        ]
                    }
                ]
            }
        },
        "/deviation/edit/{deviationid}": {
            "post": {
                "operationId": "deviation_edit",
                "tags": [
                    "deviation"
                ],
                "summary": "Edit deviation",
                "description": "Edit deviation.",
                "security": [
                    {
                        "oauth2AuthorizationCode": [
                            "publish",
                            "stash"
                        ]
                    }
                ]
            }
        },
        "/deviation/journal/create": {
            "post": {
                "operationId": "deviation_journal_create",
                "tags": [
                    "deviation"
                ],
                "summary": "Journal create",
                "description": "Create journal",
                "security": [
                    {
                        "oauth2AuthorizationCode": [
                            "user.manage"
                        ]
                    }
                ]
            }
        },
        "/deviation/journal/update/{deviationid}": {
            "post": {
                "operationId": "deviation_journal_update",
                "tags": [
                    "deviation"
                ],
                "summary": "Update journal",
                "description": "Update journal. \n            All values left empty, except cover image deviation id, will have the corresponding fields cleared. \n            To keep a field value send the old one. To clear cover image deviation id value - pass `reset_cover_image_deviation_id` param with value `true`",
                "security": [
                    {
                        "oauth2AuthorizationCode": [
                            "user.manage"
                        ]
                    }
                ]
            }
        },
        "/deviation/literature/create": {
            "post": {
                "operationId": "deviation_literature_create",
                "tags": [
                    "deviation"
                ],
                "summary": "Create literature",
                "description": "Create literature",
                "security": [
                    {
                        "oauth2AuthorizationCode": [
                            "user.manage"
                        ]
                    }
                ]
            }
        },
        "/deviation/literature/update/{deviationid}": {
            "post": {
                "operationId": "deviation_literature_update",
                "tags": [
                    "deviation"
                ],
                "summary": "Update literature",
                "description": "Update literature. Note: null/empty values will have the corresponding fields cleared. To keep a field value send the old one.",
                "security": [
                    {
                        "oauth2AuthorizationCode": [
                            "user.manage"
                        ]
                    }
                ]
            }
        },
        "/deviation/metadata": {
            "get": {
                "operationId": "deviation_metadata",
                "tags": [
                    "deviation"
                ],
                "summary": "Deviation Metadata",
                "description": "Fetch deviation metadata for a set of deviations",
                "security": [
                    {
                        "oauth2AuthorizationCodeOrClientCredentials": [
                            "browse"
                        ]
                    }
                ]
            }
        },
        "/deviation/whofaved": {
            "get": {
                "operationId": "deviation_whofaved",
                "tags": [
                    "deviation"
                ],
                "summary": "Who Faved",
                "description": "Fetch a list of users who faved the deviation",
                "security": [
                    {
                        "oauth2AuthorizationCodeOrClientCredentials": [
                            "browse"
                        ]
                    }
                ]
            }
        },
        "/deviation/{deviationid}": {
            "get": {
                "operationId": "deviation_single",
                "tags": [
                    "deviation"
                ],
                "summary": "Deviation (Single)",
                "description": "Fetch a deviation",
                "security": [
                    {
                        "oauth2AuthorizationCodeOrClientCredentials": [
                            "browse"
                        ]
                    }
                ]
            }
        },
        "/feed/home": {
            "get": {
                "operationId": "feed_home",
                "tags": [
                    "feed"
                ],
                "summary": "Feed Home",
                "description": "Fetch Watch Feed",
                "security": [
                    {
                        "oauth2AuthorizationCode": [
                            "feed"
                        ]
                    }
                ]
            }
        },
        "/feed/home/{bucketid}": {
            "get": {
                "operationId": "feed_home_bucket",
                "tags": [
                    "feed"
                ],
                "summary": "Feed Home Bucket",
                "description": "Fetch content related to a Watch event",
                "security": [
                    {
                        "oauth2AuthorizationCode": [
                            "feed"
                        ]
                    }
                ]
            }
        },
        "/feed/notifications": {
            "get": {
                "operationId": "feed_notifications",
                "tags": [
                    "feed"
                ],
                "summary": "Feed Notifications",
                "description": "Fetch Notifications",
                "security": [
                    {
                        "oauth2AuthorizationCode": [
                            "feed"
                        ]
                    }
                ]
            }
        },
        "/feed/profile": {
            "get": {
                "operationId": "feed_profile",
                "tags": [
                    "feed"
                ],
                "summary": "Profile Feed",
                "description": "Fetch Profile Feed",
                "security": [
                    {
                        "oauth2AuthorizationCode": [
                            "feed"
                        ]
                    }
                ]
            }
        },
        "/feed/settings": {
            "get": {
                "operationId": "feed_settings",
                "tags": [
                    "feed"
                ],
                "summary": "Feed Settings",
                "description": "Get feed settings",
                "security": [
                    {
                        "oauth2AuthorizationCode": [
                            "feed"
                        ]
                    }
                ]
            }
        },
        "/feed/settings/update": {
            "post": {
                "operationId": "feed_settings_update",
                "tags": [
                    "feed"
                ],
                "summary": "Feed Settings Update",
                "description": "Change feed settings",
                "security": [
                    {
                        "oauth2AuthorizationCode": [
                            "feed"
                        ]
                    }
                ]
            }
        },
        "/gallery/all": {
            "get": {
                "operationId": "gallery_all",
                "tags": [
                    "gallery"
                ],
                "summary": "Gallery All",
                "description": "Get the \"all\" view of a users gallery",
                "security": [
                    {
                        "oauth2AuthorizationCodeOrClientCredentials": [
                            "browse"
                        ]
                    }
                ]
            }
        },
        "/gallery/folders": {
            "get": {
                "operationId": "gallery_folders",
                "tags": [
                    "gallery"
                ],
                "summary": "Gallery Folders",
                "description": "Fetch gallery folders",
                "security": [
                    {
                        "oauth2AuthorizationCodeOrClientCredentials": [
                            "browse"
                        ]
                    }
                ]
            }
        },
        "/gallery/folders/copy_deviations": {
            "post": {
                "operationId": "gallery_folders_copy_deviations",
                "tags": [
                    "gallery"
                ],
                "summary": "Copy Deviations to folder",
                "description": "Copy a list of deviations to a folder destination",
                "security": [
                    {
                        "oauth2AuthorizationCode": [
                            "browse",
                            "gallery"
                        ]
                    }
                ]
            }
        },
        "/gallery/folders/create": {
            "post": {
                "operationId": "gallery_folders_create",
                "tags": [
                    "gallery"
                ],
                "summary": "Gallery Folders Create",
                "description": "Create new gallery folders.",
                "security": [
                    {
                        "oauth2AuthorizationCode": [
                            "browse",
                            "gallery"
                        ]
                    }
                ]
            }
        },
        "/gallery/folders/move": {
            "post": {
                "operationId": "gallery_folders_move",
                "tags": [
                    "gallery"
                ],
                "summary": "Move folder",
                "description": "Move folder to another folder",
                "security": [
                    {
                        "oauth2AuthorizationCode": [
                            "browse",
                            "gallery"
                        ]
                    }
                ]
            }
        },
        "/gallery/folders/move_deviations": {
            "post": {
                "operationId": "gallery_folders_move_deviations",
                "tags": [
                    "gallery"
                ],
                "summary": "Move Deviations to folder",
                "description": "Copy a list of deviations to a folder destination",
                "security": [
                    {
                        "oauth2AuthorizationCode": [
                            "browse",
                            "gallery"
                        ]
                    }
                ]
            }
        },
        "/gallery/folders/remove/{folderid}": {
            "post": {
                "operationId": "gallery_folders_remove",
                "tags": [
                    "gallery"
                ],
                "summary": "Gallery Folders Remove",
                "description": "Delete gallery folder",
                "security": [
                    {
                        "oauth2AuthorizationCode": [
                            "browse",
                            "gallery"
                        ]
                    }
                ]
            }
        },
        "/gallery/folders/remove_deviations": {
            "post": {
                "operationId": "gallery_folders_remove_deviations",
                "tags": [
                    "gallery"
                ],
                "summary": "Remove deviations from folder",
                "description": "Remove a list of deviations from a gallery folder",
                "security": [
                    {
                        "oauth2AuthorizationCode": [
                            "browse",
                            "gallery"
                        ]
                    }
                ]
            }
        },
        "/gallery/folders/update": {
            "post": {
                "operationId": "gallery_folders_update",
                "tags": [
                    "gallery"
                ],
                "summary": "Update details",
                "security": [
                    {
                        "oauth2AuthorizationCode": [
                            "browse",
                            "gallery"
                        ]
                    }
                ]
            }
        },
        "/gallery/folders/update_deviation_order": {
            "post": {
                "operationId": "gallery_folders_update_deviation_order",
                "tags": [
                    "gallery"
                ],
                "summary": "Update deviation order",
                "description": "Update order of deviation in folder",
                "security": [
                    {
                        "oauth2AuthorizationCode": [
                            "browse",
                            "gallery"
                        ]
                    }
                ]
            }
        },
        "/gallery/folders/update_order": {
            "post": {
                "operationId": "gallery_folders_update_order",
                "tags": [
                    "gallery"
                ],
                "summary": "Reposition a folder",
                "description": "Rearrange the position of folders",
                "security": [
                    {
                        "oauth2AuthorizationCode": [
                            "browse",
                            "gallery"
                        ]
                    }
                ]
            }
        },
        "/gallery/{folderid}": {
            "get": {
                "operationId": "gallery",
                "tags": [
                    "gallery"
                ],
                "summary": "Gallery",
                "description": "Fetch gallery folder contents",
                "security": [
                    {
                        "oauth2AuthorizationCodeOrClientCredentials": [
                            "browse"
                        ]
                    }
                ]
            }
        },
        "/messages/delete": {
            "post": {
                "operationId": "messages_delete",
                "tags": [
                    "messages"
                ],
                "summary": "Messages Delete",
                "description": "Delete a message or a message stack",
                "security": [
                    {
                        "oauth2AuthorizationCode": [
                            "message"
                        ]
                    }
                ]
            }
        },
        "/messages/feed": {
            "get": {
                "operationId": "messages_feed",
                "tags": [
                    "messages"
                ],
                "summary": "Messages Feed",
                "description": "Feed of all messages",
                "security": [
                    {
                        "oauth2AuthorizationCode": [
                            "message"
                        ]
                    }
                ]
            }
        },
        "/messages/feedback": {
            "get": {
                "operationId": "messages_feedback",
                "tags": [
                    "messages"
                ],
                "summary": "Feedback",
                "description": "Fetch feedback messages",
                "security": [
                    {
                        "oauth2AuthorizationCode": [
                            "message"
                        ]
                    }
                ]
            }
        },
        "/messages/feedback/{stackid}": {
            "get": {
                "operationId": "messages_feedback_stack",
                "tags": [
                    "messages"
                ],
                "summary": "Feedback Stack",
                "description": "Fetch messages in a stack",
                "security": [
                    {
                        "oauth2AuthorizationCode": [
                            "message"
                        ]
                    }
                ]
            }
        },
        "/messages/mentions": {
            "get": {
                "operationId": "messages_mentions",
                "tags": [
                    "messages"
                ],
                "summary": "Mentions",
                "description": "Fetch mention messages",
                "security": [
                    {
                        "oauth2AuthorizationCode": [
                            "message"
                        ]
                    }
                ]
            }
        },
        "/messages/mentions/{stackid}": {
            "get": {
                "operationId": "messages_mentions_stack",
                "tags": [
                    "messages"
                ],
                "summary": "Mentions Stack",
                "description": "Fetch messages in a stack",
                "security": [
                    {
                        "oauth2AuthorizationCode": [
                            "message"
                        ]
                    }
                ]
            }
        },
        "/notes": {
            "get": {
                "operationId": "notes",
                "tags": [
                    "notes"
                ],
                "summary": "Notes",
                "description": "Fetch notes",
                "security": [
                    {
                        "oauth2AuthorizationCode": [
                            "note"
                        ]
                    }
                ]
            }
        },
        "/notes/delete": {
            "post": {
                "operationId": "notes_delete",
                "tags": [
                    "notes"
                ],
                "summary": "Notes Delete",
                "description": "Delete a note or notes",
                "security": [
                    {
                        "oauth2AuthorizationCode": [
                            "note"
                        ]
                    }
                ]
            }
        },
        "/notes/folders": {
            "get": {
                "operationId": "notes_folders",
                "tags": [
                    "notes"
                ],
                "summary": "Notes Folders",
                "description": "Fetch note folders",
                "security": [
                    {
                        "oauth2AuthorizationCode": [
                            "note"
                        ]
                    }
                ]
            }
        },
        "/notes/folders/create": {
            "post": {
                "operationId": "notes_folders_create",
                "tags": [
                    "notes"
                ],
                "summary": "Notes Folders Create",
                "description": "Create new folder",
                "security": [
                    {
                        "oauth2AuthorizationCode": [
                            "note"
                        ]
                    }
                ]
            }
        },
        "/notes/folders/remove/{folderid}": {
            "post": {
                "operationId": "notes_folders_remove",
                "tags": [
                    "notes"
                ],
                "summary": "Notes Folders Remove",
                "description": "Delete note folder",
                "security": [
                    {
                        "oauth2AuthorizationCode": [
                            "note"
                        ]
                    }
                ]
            }
        },
        "/notes/folders/rename/{folderid}": {
            "post": {
                "operationId": "notes_folders_rename",
                "tags": [
                    "notes"
                ],
                "summary": "Notes Folders Rename",
                "description": "Rename a folder",
                "security": [
                    {
                        "oauth2AuthorizationCode": [
                            "note"
                        ]
                    }
                ]
            }
        },
        "/notes/mark": {
            "post": {
                "operationId": "notes_mark",
                "tags": [
                    "notes"
                ],
                "summary": "Notes Mark",
                "description": "Mark notes",
                "security": [
                    {
                        "oauth2AuthorizationCode": [
                            "note"
                        ]
                    }
                ]
            }
        },
        "/notes/move": {
            "post": {
                "operationId": "notes_move",
                "tags": [
                    "notes"
                ],
                "summary": "Notes Move",
                "description": "Move notes to a folder",
                "security": [
                    {
                        "oauth2AuthorizationCode": [
                            "note"
                        ]
                    }
                ]
            }
        },
        "/notes/send": {
            "post": {
                "operationId": "notes_send",
                "tags": [
                    "notes"
                ],
                "summary": "Notes Send",
                "description": "Send a note",
                "security": [
                    {
                        "oauth2AuthorizationCode": [
                            "note"
                        ]
                    }
                ]
            }
        },
        "/notes/{noteid}": {
            "get": {
                "operationId": "notes_single",
                "tags": [
                    "notes"
                ],
                "summary": "Notes (Single)",
                "description": "Fetch a single note",
                "security": [
                    {
                        "oauth2AuthorizationCode": [
                            "note"
                        ]
                    }
                ]
            }
        },
        "/placebo": {
            "get": {
                "operationId": "placebo",
                "tags": [
                    "util"
                ],
                "summary": "Placebo",
                "description": "Placebo call to confirm your access_token is valid"
            }
        },
        "/stash/publish": {
            "post": {
                "operationId": "stash_publish",
                "tags": [
                    "stash"
                ],
                "summary": "Sta.sh Publish",
                "description": "Publish a Sta.sh item to deviantART",
                "security": [
                    {
                        "oauth2AuthorizationCode": [
                            "publish",
                            "stash"
                        ]
                    }
                ]
            }
        },
        "/stash/submit": {
            "post": {
                "operationId": "stash_submit",
                "tags": [
                    "stash"
                ],
                "summary": "Sta.sh Submit",
                "description": "Submit files to Sta.sh or modify existing files",
                "security": [
                    {
                        "oauth2AuthorizationCode": [
                            "basic",
                            "stash"
                        ]
                    }
                ]
            }
        },
        "/user/friends/search": {
            "get": {
                "operationId": "user_friends_search",
                "tags": [
                    "user"
                ],
                "summary": "Friends Search",
                "description": "Search friends by username",
                "security": [
                    {
                        "oauth2AuthorizationCodeOrClientCredentials": [
                            "browse"
                        ]
                    }
                ]
            }
        },
        "/user/friends/unwatch/{username}": {
            "get": {
                "operationId": "user_friends_unwatch",
                "tags": [
                    "user"
                ],
                "summary": "Friends Unwatch",
                "description": "Unwatch a user",
                "security": [
                    {
                        "oauth2AuthorizationCode": [
                            "browse",
                            "user.manage"
                        ]
                    }
                ]
            }
        },
        "/user/friends/watch/{username}": {
            "post": {
                "operationId": "user_friends_watch",
                "tags": [
                    "user"
                ],
                "summary": "Friends Watch",
                "description": "Watch a user",
                "security": [
                    {
                        "oauth2AuthorizationCode": [
                            "browse",
                            "user.manage"
                        ]
                    }
                ]
            }
        },
        "/user/friends/watching/{username}": {
            "get": {
                "operationId": "user_friends_watching",
                "tags": [
                    "user"
                ],
                "summary": "Friends Watching",
                "description": "Check if user is being watched by the given user",
                "security": [
                    {
                        "oauth2AuthorizationCode": [
                            "browse",
                            "user"
                        ]
                    }
                ]
            }
        },
        "/user/friends/{username}": {
            "get": {
                "operationId": "user_friends",
                "tags": [
                    "user"
                ],
                "summary": "Friends",
                "description": "Get the users list of friends",
                "security": [
                    {
                        "oauth2AuthorizationCodeOrClientCredentials": [
                            "browse"
                        ]
                    }
                ]
            }
        },
        "/user/profile/avatar/update": {
            "post": {
                "operationId": "user_profile_avatar_update",
                "tags": [
                    "user"
                ],
                "summary": "Avatar Update",
                "description": "Upload a new avatar",
                "security": [
                    {
                        "oauth2AuthorizationCode": [
                            "browse",
                            "user.manage"
                        ]
                    }
                ]
            }
        },
        "/user/profile/posts": {
            "get": {
                "operationId": "user_profile_posts",
                "tags": [
                    "user"
                ],
                "summary": "User Posts",
                "description": "Will return all journals & status updates for a given user in a single feed.",
                "security": [
                    {
                        "oauth2AuthorizationCodeOrClientCredentials": [
                            "browse"
                        ]
                    }
                ]
            }
        },
        "/user/profile/update": {
            "post": {
                "operationId": "user_profile_update",
                "tags": [
                    "user"
                ],
                "summary": "Profile Update",
                "description": "Update the users profile information",
                "security": [
                    {
                        "oauth2AuthorizationCode": [
                            "browse",
                            "user.manage"
                        ]
                    }
                ]
            }
        },
        "/user/profile/{username}": {
            "get": {
                "operationId": "user_profile",
                "tags": [
                    "user"
                ],
                "summary": "Profile",
                "description": "Get user profile information",
                "security": [
                    {
                        "oauth2AuthorizationCodeOrClientCredentials": [
                            "browse"
                        ]
                    }
                ]
            }
        },
        "/user/statuses/post": {
            "post": {
                "operationId": "user_statuses_post",
                "tags": [
                    "user"
                ],
                "summary": "User Statuses Post",
                "description": "Post a status",
                "security": [
                    {
                        "oauth2AuthorizationCode": [
                            "user.manage"
                        ]
                    }
                ]
            }
        },
        "/user/tiers/{username}": {
            "get": {
                "operationId": "user_tiers",
                "tags": [
                    "user"
                ],
                "summary": "Get user's Tier list",
                "security": [
                    {
                        "oauth2AuthorizationCode": [
                            "basic"
                        ]
                    }
                ]
            }
        },
        "/user/watchers/{username}": {
            "get": {
                "operationId": "user_watchers",
                "tags": [
                    "user"
                ],
                "summary": "User Watchers",
                "description": "Get the user's list of watchers",
                "security": [
                    {
                        "oauth2AuthorizationCodeOrClientCredentials": [
                            "browse"
                        ]
                    }
                ]
            }
        },
        "/user/whoami": {
            "get": {
                "operationId": "user_whoami",
                "tags": [
                    "user"
                ],
                "summary": "Who Am I",
                "description": "Fetch user info of authenticated user",
                "security": [
                    {
                        "oauth2AuthorizationCode": [
                            "basic",
                            "user"
                        ]
                    }
                ]
            }
        },
        "/user/whois": {
            "post": {
                "operationId": "user_whois",
                "tags": [
                    "user"
                ],
                "summary": "Who Is",
                "description": "Fetch user info for given usernames",
                "security": [
                    {
                        "oauth2AuthorizationCode": [
                            "browse"
                        ]
                    }
                ]
            }
        }
    },
    "components": {
        "securitySchemes": {
            "oauth2AuthorizationCode": {
                "type": "oauth2",
                "flows": {
                    "authorizationCode": {
                        "authorizationUrl": "https://www.deviantart.com/oauth2/authorize",
                        "tokenUrl": "https://www.deviantart.com/oauth2/token",
                        "scopes": {
                            "basic": "OAuth scope: basic",
                            "browse": "OAuth scope: browse",
                            "collection": "OAuth scope: collection",
                            "comment.manage": "OAuth scope: comment.manage",
                            "comment.post": "OAuth scope: comment.post",
                            "feed": "OAuth scope: feed",
                            "gallery": "OAuth scope: gallery",
                            "message": "OAuth scope: message",
                            "note": "OAuth scope: note",
                            "publish": "OAuth scope: publish",
                            "stash": "OAuth scope: stash",
                            "user": "OAuth scope: user",
                            "user.manage": "OAuth scope: user.manage"
                        }
                    }
                }
            },
            "oauth2AuthorizationCodeOrClientCredentials": {
                "type": "oauth2",
                "flows": {
                    "authorizationCode": {
                        "authorizationUrl": "https://www.deviantart.com/oauth2/authorize",
                        "tokenUrl": "https://www.deviantart.com/oauth2/token",
                        "scopes": {
                            "basic": "OAuth scope: basic",
                            "browse": "OAuth scope: browse",
                            "collection": "OAuth scope: collection",
                            "comment.manage": "OAuth scope: comment.manage",
                            "comment.post": "OAuth scope: comment.post",
                            "feed": "OAuth scope: feed",
                            "gallery": "OAuth scope: gallery",
                            "message": "OAuth scope: message",
                            "note": "OAuth scope: note",
                            "publish": "OAuth scope: publish",
                            "stash": "OAuth scope: stash",
                            "user": "OAuth scope: user",
                            "user.manage": "OAuth scope: user.manage"
                        }
                    },
                    "clientCredentials": {
                        "tokenUrl": "https://www.deviantart.com/oauth2/token",
                        "scopes": {
                            "basic": "OAuth scope: basic",
                            "browse": "OAuth scope: browse",
                            "collection": "OAuth scope: collection",
                            "comment.manage": "OAuth scope: comment.manage",
                            "comment.post": "OAuth scope: comment.post",
                            "feed": "OAuth scope: feed",
                            "gallery": "OAuth scope: gallery",
                            "message": "OAuth scope: message",
                            "note": "OAuth scope: note",
                            "publish": "OAuth scope: publish",
                            "stash": "OAuth scope: stash",
                            "user": "OAuth scope: user",
                            "user.manage": "OAuth scope: user.manage"
                        }
                    }
                }
            }
        }
    },
    "tags": [
        {
            "name": "browse"
        },
        {
            "name": "collections"
        },
        {
            "name": "comments"
        },
        {
            "name": "data"
        },
        {
            "name": "deviation"
        },
        {
            "name": "feed"
        },
        {
            "name": "gallery"
        },
        {
            "name": "messages"
        },
        {
            "name": "notes"
        },
        {
            "name": "stash"
        },
        {
            "name": "user"
        },
        {
            "name": "util"
        }
    ]
}
